// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/login.tsx";
import * as $$0 from "./islands/Login.tsx";

const manifest = {
    routes: {
        "./routes/_middleware.ts": $0,
        "./routes/login.tsx": $1,
    },
    islands: {
        "./islands/Login.tsx": $$0,
    },
    baseUrl: import.meta.url,
};

export default manifest;
